# Related scripts
trainScriptName: condition_SN_multiscale_sampleonebyone
gScriptName: Conditional_Generator_asm
dScriptName: Conditional_Discriminator_Projection

# Training information
totalStep: 400000
batchSize_list: [8,4,1] 
switch_step_list: [0, 100000, 200000]
imCropSize_list: [256, 512, 768]
max2Keep: 10
movingAverage: 0.05
dSuccessThreshold: 0.8

# Dataset
selectedStyleDir: ['berthe-morisot','edvard-munch',
                   'ernst-ludwig-kirchner','jackson-pollock','kandinsky','monet',
                   'nicholas','paul-cezanne','picasso','samuel','vangogh']

selectedContentDir: ['img']

# Optimizer
gLr: 0.0002
dLr: 0.0002
# lrDecay: 0.1
# lrDecayStep: 100
# lrDecayEnable: True
beta1: 0.9
beta2: 0.999
dStep: 3
gStep: 1
featureWeight: 50.0
transformWeight: 50.0
layersWeight: [1.0, 1.0, 1.0, 1.0, 1.0]

# Model hyper-parameters
GConvDim: 32
DConvDim: 32
GKS: 3
DKS: 5
resNum: 8
GEncActName: leakyrelu
GDecActName: relu
GOutActName: tanh
DActName: leakyrelu

# Log 
logStep: 1000
sampleStep: 2000
modelSaveStep: 5000
useTensorboard: True